---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-deploy
spec:
  replicas: 
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - image: aivarassu/vote_app:0.0.26
        ports:
        - containerPort: 80
        name: vote-container

