kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-to-redis
spec:
  podSelector:
    matchLabels:
      app: 
  ingress:
  - ports:
    - port: 
    from:
      - podSelector:
          matchLabels:
            app: 
            
