---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: -pv-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: 
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: Gi
