---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vote
   
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - image: aivarassu/vote_app:0.0.
        ports:
        - containerPort: 80
        name: vote
