---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - image: postgres:9.4
        env:
          - name: POSTGRES_HOST_AUTH_METHOD
            value: trust
          - name: 
            value: 
        name: 
        ports:
          - containerPort: 
        volumeMounts:
        - mountPath: 
          name:  
      volumes:
      - name: 
        emptyDir: {} 
---        
apiVersion: v1
kind: Service
metadata:
  name: 
spec:
  type: ClusterIP
  ports:
  - port: 
    targetPort: 
  selector:
    app: db
