---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: 
spec:
  replicas: 
  template:
    metadata:
      labels:
        app: 
    spec:
      containers:
      - image: kubernetes/
        name: 
        ports:
          - containerPort: 
        env:
          - name: 
            value: 
---
apiVersion: v1
kind: Service
metadata:
  name: 
spec:
  type: ClusterIP
  ports:
  - port: 
    targetPort: 
  selector:
    app: 
