---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - image: aivarassu/result_app:0.0.27
        ports:
        - containerPort: 80
        name: result-container
---
apiVersion: v1
kind: Service
metadata:
  name: result-svc
spec:
  type: ClusterIP
  ports:
  - port: 5001
    targetPort: 80
  selector:
    app: result
