---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: 
spec:
  replicas: 
  selector:
    matchLabels:
      app: 
  template:
    metadata:
      labels:
        app: 
    spec:
      containers:
      - image: aivarassu/
        ports:
        - containerPort: 
        name: 
---
apiVersion: v1
kind: Service
metadata:
  name: 
spec:
  type: ClusterIP
  ports:
  - port: 
    targetPort: 
  selector:
    app: 
