apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deploy

spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - image: dockersamples/examplevotingapp_worker
        name: worker-container
