---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: kubernetes/redis:v1
        name: redis
        ports:
          - containerPort: 6379
        env:
        - name: MASTER
          valueFrom:
            secretKeyRef:
               name: redis-secret
               key: redis-status
        volumeMounts:
        - mountPath: /redis-master
          name: config
        resources:
          limits:
            memory: "M"
            cpu: "m"
      volumes:
        - name: config
          configMap:
            name: redis-configmap
            items:
            - key: redis-config
              path: redis.conf    
